import { BorderThemeOption, BorderThemeId } from './types';

export const BORDER_THEMES: BorderThemeOption[] = [
  {
    id: 'classic',
    name: 'Classic Studio',
    category: 'Minimalist',
    tagline: 'Clean rounded poster with timeless framing',
    emoji: '🔲',
    badge: 'Standard',
    defaultColor: '#1d4ed8',
    defaultBg: '#ffffff',
    defaultCenterIcon: 'none',
    defaultTitle: 'Scan to Connect',
    bannerText: '',
  },
  {
    id: 'birthday',
    name: 'Birthday Bash',
    category: 'Celebration',
    tagline: 'Festive balloons, celebratory ribbons & 3D confetti',
    emoji: '🎂',
    badge: 'Popular',
    defaultColor: '#e11d48',
    defaultBg: '#fff1f2',
    defaultCenterIcon: 'star',
    defaultTitle: 'Happy Birthday! Scan for Surprise 🎈',
    bannerText: '🎉 IT’S CELEBRATION TIME 🎉',
    has3DConfetti: true,
  },
  {
    id: 'wedding',
    name: 'Wedding & Love',
    category: 'Romantic',
    tagline: 'Botanical laurel wreaths & champagne gold filigree',
    emoji: '💍',
    badge: 'Elegant',
    defaultColor: '#9f1239',
    defaultBg: '#fffdfa',
    defaultCenterIcon: 'star',
    defaultTitle: 'Save Our Date • Scan to RSVP',
    bannerText: '✨ TOGETHER FOREVER • SAVE OUR DATE ✨',
  },
  {
    id: 'cyberpunk',
    name: 'Cyber 3D Neon',
    category: 'Futuristic',
    tagline: 'Glowing HUD reticles, neon brackets & matrix grid',
    emoji: '⚡',
    badge: '3D Sci-Fi',
    defaultColor: '#06b6d4',
    defaultBg: '#090d16',
    defaultCenterIcon: 'link',
    defaultTitle: 'System Terminal // Access Granted',
    bannerText: '[ SYSTEM PROTOCOL 01 // SECURE KEY ]',
  },
  {
    id: 'vip_gold',
    name: 'VIP Gold Crest',
    category: 'Luxury Gala',
    tagline: 'Double gilded frame with royal crowns & gold luster',
    emoji: '👑',
    badge: 'Luxury',
    defaultColor: '#b45309',
    defaultBg: '#1c1917',
    defaultCenterIcon: 'star',
    defaultTitle: 'Exclusive VIP Access Pass',
    bannerText: '★ PREMIER INVITATION ONLY ★',
  },
  {
    id: 'food_bistro',
    name: 'Bistro & Dining',
    category: 'Hospitality',
    tagline: 'Artisan menu border with chef & cutlery seals',
    emoji: '🍽️',
    badge: 'Restaurant',
    defaultColor: '#c2410c',
    defaultBg: '#fffbeb',
    defaultCenterIcon: 'food',
    defaultTitle: 'Scan to View Today’s Fresh Menu',
    bannerText: '• BON APPÉTIT • CHEF SPECIALS •',
  },
  {
    id: 'party_fun',
    name: 'Party & Festival',
    category: 'Festival',
    tagline: 'Electric neon sparkles, party stars & wavy rim',
    emoji: '🎪',
    badge: 'Vibrant',
    defaultColor: '#7c3aed',
    defaultBg: '#faf5ff',
    defaultCenterIcon: 'star',
    defaultTitle: 'Party Admission • VIP Wristband',
    bannerText: '♫ FESTIVAL ENTRANCE PASS ♫',
    has3DConfetti: true,
  },
];

export const getBorderThemeById = (id: BorderThemeId): BorderThemeOption => {
  return BORDER_THEMES.find((t) => t.id === id) || BORDER_THEMES[0];
};
